version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_CONSOLE_ADDRESS: ":9001"
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - app-network

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"  # Spark Master UI
      - "4040:4040"  # Spark Driver UI (if running locally)
    depends_on:
      - minio
    networks:
      - app-network

volumes:
  minio-data:

networks:
  app-network:
    driver: bridge